- js/cycle.min.js
- src/js/cycle.js
We'll need to circle back around to the slideshow implementation as a whole eventually, but for now, this should get the slideshows running for Jon's meeting this week.
@jeremyfelt #reviewmerge?
> [PR] Add Cycle2 options for manual implementations

- css/00-banner.css
- functions.php
- package.json
- style.css
- woocommerce.php
> WC Cleanup

- css/00-banner.css
- package.json
- style.css
- woocommerce.php
converting template to display 1-column instead of 2 for product page
> WooCommerce 1-Col Product Page

- Gruntfile.js
- admin-css/woocommerce-product-list-table.css
- composer.json
- includes/class-wsu-press-extended-woocommerce.php
- package.json
- phpcs.ruleset.xml
- src/admin-css/woocommerce-product-list-table.css
- woocommerce/single-product/meta.php
Per client request, change instances of `SKU` to `SKU/ISBN`.
> [PR] SKU/ISBN

- includes/class-wsu-press-extended-woocommerce.php
> [PR] Short quotes

- functions.php
- includes/class-wsu-press-product-search-shortcode.php
Fixes #16.
Tried to make this search our added meta data, too, but I don't think it worked. :man_shrugging:
> [PR] WooCommerce product search shortcode

- functions.php
- woocommerce/single-product/title.php
Part of #14 that I almost forgot :)
> [PR] Link authors to their term page

- css/00-banner.css
- functions.php
- package.json
- parts/headers.php
- style.css
updating links at top, changing site slogan
> Header Changes

- articles/post.php
This replacement implements a new "More" output after the content paragraph. The rest is a copy of the WSU Spine Parent Theme's `articles/post.php` file.
Fixes #43.
> [PR] Replace default Spine post template

- includes/class-wsu-press-extended-woocommerce.php
> [PR] Remove the shipping rate label on the cart and checkout pages

- articles/post.php
fixes the forced cropping/dimensions of book covers when searching for
books in the blog sidebar
@philcable #reviewmerge?
> search results-book covers

- articles/post.php
revise the formatting of more buttons in the search results
@philcable #reviewmerge?
> more button for search results

- functions.php
> [PR] Filter the "Add to Cart" button text

- functions.php
Per @jbickelhaupt's request, to be merged after https://github.com/washingtonstateuniversity/wsupress.wsu.edu/pull/68.
> [PR] Thumbnail wrapper

- css/00-banner.css
- functions.php
- package.json
- style.css
Hoping this covers all the bases now... though I could swear everything was working as expected last time. ¯\\\_(ツ)_/¯
> [PR] Header adjustments

- functions.php
Changing button text from Buy to Details
> Change button text

- functions.php
- parts/headers.php
This change was suggested and decided on during a design review :)
> [PR] Display the logo and site tagline on all pages

- css/00-banner.css
- functions.php
- package-lock.json
- package.json
- style.css
- templates/search.php
Copied from the murrow.wsu.edu theme
> [PR] Add a template for the search page

- css/98-search-results.css
- style.css
- templates/search.php
Well, this is one way to do it...
> [PR] Search results output and design

- woocommerce/single-product/title.php
I messed this up in the last pull request 😅
> [PR] Fix author meta retrieval and display

- includes/search.php
Include subtitle and author name.
> [PR] Filter data sent to Elasticsearch for a product record

- woocommerce/emails/customer-processing-order.php
- Update customer-processing-order.php to 3.5.4
> [PR] Fix order template
